### ISSUE TITLE
SDRplay device support in QRadioLink AppImage

### ISSUE THREAD

**Issue by AsciiWolf** [qradiolink/qradiolink#112]
Fedora 35, QRadioLink 0.8.6-2 AppImage.

SDRplay RSPdx does not seem to work and always returns: `[Fatal] Could not init RX device, check settings and restart`

I am using the same RX device args as in Gqrx where everything works fine: `soapy=0,driver=sdrplay,serial=xxx` (replaced the actual serial number with `xxx`)

My RSPdx also worked fine in every other SDR software I tried that supported SoapySDR; QRadioLink is the only one where it does not work for some reason.

**Comment by kantooon** [comment]
I don't use the appimage or this particular device, but I think I can offer a guess regarding what's happening.

SoapySDR modules, unlike the other libraries used by the project, are not linked directly (they are not build time dependencies). Instead, SoapySDR dynamically loads them at runtime.

Because of this, the appimage build script (which is included in the Debian Travis action) cannot detect modules as dependencies and can't include them in the appimage. A possible way to solve this might be to build and install the module somewhere like /usr/local/lib/ but take care that it matches the SoapySDR version used by the appimage (in this case version 0.7). Then it might or might not be necessary to inform the appimage executable of additional libraries through LD_PRELOAD or LD_LIBRARY_PATH.
 
Since I don't have any experience using appimages, this is something that you may need to research, but if you do find a solution, please leave a comment here too for the benefit of other users.
