### ISSUE TITLE
[Issue] Intermittent sound since QT audio implementation

### ISSUE THREAD

**Issue by Radiomix2000** [qradiolink/qradiolink#58]
I checked on different machines with Ubuntu 19.04, and the problem persists.
Issue started from v. 0.8.1-1.
When start RX in Qradiolink, the repeating message occurs
`ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred`
I hear the sound, but it's intermittent.
Seems to be audiobuffer size issue in OS? How is possible to correct it?

**Comment by kantooon** [comment]
Ok, thanks for letting me know. I could only test with Pulseaudio until now. I'll try to see what's going on with Alsa. Definitely a buffer size issue, but probably not in the OS, in the Qt audio implementation. Unfortunately with Qt audio I don't have very low level control of the options, but you can play with several options in .asoundrc:
       period_time 0
       period_size 2048
       buffer_size 65536
       buffer_time 0
       periods 128

Let me know if any of these help so I can add them to the docs. Normally I recommend everyone to use Pulseaudio which comes default in most recent distros but still want to support other audio layers which is why I moved to Qt audio.

**Comment by Radiomix2000** [comment]
So, mine working .asounrc config is
```
period_time 0
period_size 1024
buffer_size 4096
rate 48000
```
.asoundrc wasn't in home directory, I created it myself.
Not sure what affected to the issue. I just took these values from alsa-project.org.

**Comment by kantooon** [comment]
So it works well with these values?

**Comment by Radiomix2000** [comment]
Yes, now sound is clear.

**Comment by kantooon** [comment]
Great, thanks, I'll update the README.

**Comment by kantooon** [comment]
Done.

**Comment by kantooon** [comment]
Seems Pulseaudio can also have some audio glitches when running at low CPU speed (~800-1000 MHz). The current workaround is to add tsched=0 to this line in /etc/pulse/default.pa:
<pre>
load-module module-udev-detect tsched=0
</pre>
To keep latency in check, I'm not willing to increase the size of the audio buffers beyond the current value of 4096.
